[package]
name = "rgrep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


#[[bin]]
#name = "regex"
#path = "src/regex.rs"  # Path to the main binary file
